### ISSUE TITLE
On Lollipop dialog flyes under bottom icons but above black bar

### ISSUE THREAD

**Issue by vovkab** [soarcn/BottomSheet#47]
subj

**Comment by soarcn** [comment]
There has a long discussion in #9 , and so far there is no good solution for this. I personally believe this is an android defect.

Do you have any suggestions?

**Comment by vovkab** [comment]
Looks like navigation bar background is moved to content in lollipop to make seamless transitions. 
As I can see easiest way to fix it would be:
1. perform content animation instead doing window animation
2. move to fragment, but this is basically (1)

p.s. or maybe try transition framework, I don't know much about it, but looks like you can control which view to exclude from animation. Maybe it something worth looking into.

**Comment by soarcn** [comment]
A simple solution is to turn the fitsSystemWindows to false, and it will of course bring some side-effects.

So far, I don't wanna put too much effort on this one, because
- 5.0+ is still a quite small scale platform
- google's product has the same defect

But feel free to find out a way out, or perhaps post a defect to google :)

I don't think transition framework would help. It is a good framework to simply the view transition animation making, but there is no secret recipe in it.
