### ISSUE TITLE
Support for orientation change

### ISSUE THREAD

**Issue by nbarraille** [soarcn/BottomSheet#66]
Hey,
It looks like because `BottomSheet` extends `Dialog` and not `DialogFragment`, there is no easy way to support orientation changes. The only way I can think of is to keep a flag in the parent activity's saved instance state bundle, and re-open it if it was previously opened, but this is weird because of the slide-in animation.
Any solution for this?
Thanks!

**Comment by ppamorim** [comment]
First: Why BottomSheet extends Dialog?

**Comment by soarcn** [comment]
There is no magic in dialogfragment, but keep a retainfragment to keep the instance state that it could restore itself after screen rotation. I tried once to change BottomSheet to dialogfragment, but there are some conflict with current interface. Anyway it worth to try, and hopefully you could pull a request for this.

In sample application, I've demonstrated how to handle screen rotation. Yes, there will be a slide-in animation, but for me it seems fine.  Keeping the interface/usage simple is the main reason I choose to extends from Dialog.

In google's implementation, they use activity instead of dialog, which has it's own pros&cons.
